#====================================================
#         spring application properties
#====================================================
server:
  port: 8085

spring:
  application:
    name: FINOLOGY